nombre=input("digite su nombre: ")
apellido=input("digite su apellido: ")
edad=input("digite su edad: ")
print("tiene estos nombres de usuario disponibles:  ")
usuario1=("@"+ nombre.capitalize() + apellido.capitalize())
print(usuario1)
usuario2=("@"+nombre+"."+apellido).lower()
print(usuario2)
usuario3=("@"+apellido+"_"+nombre+"_"+edad).lower()
print(usuario3)